# Generated by Django 4.1 on 2022-09-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appthing', '0002_rename_calorie_fooditem_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
