# Generated by Django 4.1 on 2022-09-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appthing', '0003_alter_fooditem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('bread, cereal', 'bread, cereal'), ('meat, fish', 'meat, fish'), ('fruits, vegetables', 'fruits, vegetables'), ('milk, dairy', 'milk, dairy'), ('fats, sugars', 'fats, sugars')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
