# Generated by Django 4.1 on 2022-09-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appthing', '0004_fooditem_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('bread/cereal', 'bread/cereal'), ('meat/fish', 'meat/fish'), ('fruits/vegetables', 'fruits/vegetables'), ('milk/dairy', 'milk/dairy'), ('fats/sugars', 'fats/sugars')], max_length=50),
        ),
    ]
